[package]
name = "pharmacare-erp"
version = "0.1.0"
description = "PharmaCare ERP - Pharmacy Inventory Management"
authors = ["you"]
edition = "2021"

[lib]
name = "pharmacare_erp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

